title: Nicholas Stirling # your name (or website title) here
logo: "/images/Stirling 2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Master's graduate specializing in machine learning,
  statistical modeling, NLP, and data-driven decision making. 
  <br><br>
  email: "nickrstirling@gmail.com"
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-stirling-3839b172/">View My LinkedIn Profile</a>


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO

tagline: "Machine Learning | Analytics | AI | Data Engineering"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
